# ====== CORE SETTINGS ======
interval_seconds: 5                 # fetch order book every 5 seconds
gcs_bucket: "bananazone"            # your GCS bucket name

exchanges:
  - name: coinbase
    quote: USD
  - name: kraken
    quote: USD

assets: [BTC, ETH, ADA, XRP]
layers: [5, 50, 100]

# ====== PUBLISH CADENCE ======
publish_1min_minutes: 5             # rebuild & publish 1m data every 5 minutes (≤5m lag)
publish_5s_minutes: 60              # compose 5s daily file every 60 minutes

# ====== PATHS (NDJSON .jsonl) ======
paths:
  # 5-second data
  five_sec_minute: "{ex}/{asset}/5s/min/{day}/{hour}/{day}T{hour}:{minute}.jsonl"  # per-minute bucket of 5s lines
  five_sec_daily:  "{ex}/{asset}/5s/{day}.jsonl"                                   # composed hourly from the per-minute files

  # 1-minute data (robust, no overwrite)
  one_min_minute:  "{ex}/{asset}/1min/min/{day}/{hour}/{day}T{hour}:{minute}.jsonl" # one line per minute (source parts)
  one_min_daily:   "{ex}/{asset}/1min/{day}.jsonl"                                   # composed from all per-minute parts
