# ====== CORE SETTINGS ======
interval_seconds: 5               # pull orderbook every 5s
gcs_bucket: "bananazone"          # <-- your bucket

exchanges:
  - name: coinbase
    quote: USD
  - name: bybit
    quote: USDT

assets: [BTC, ETH, ADA, XRP]
layers: [5, 50, 100]

# ====== PUBLISH CADENCE ======
publish_1min_minutes: 5           # near-live 1m daily must be <= 5 minutes behind
publish_5s_minutes: 60            # compose 5s daily hourly (you said near-live not needed here)

# ====== PATHS (NDJSON .jsonl) ======
paths:
  five_sec_minute: "{ex}/{asset}/5s/min/{day}/{hour}/{day}T{hour}:{minute}.jsonl"  # per-minute file; we append each 5s tick into it
  five_sec_daily:  "{ex}/{asset}/5s/{day}.jsonl"                                    # built by compose from the minute files
  one_min_daily:   "{ex}/{asset}/1min/{day}.jsonl"                                  # daily 1m file (upserted <= every 5m)
